base_path: &base_path "D:/Code/graduation_design/"
# base_path: &base_path "/Users/horiki/Code/graduation_design/"
# base_path: &base_path "/root/autodl-tmp/graduation_design/"

data:
  maxlen: 20
  is_sample: false
  base_model_topk: 100
  device: &device "cuda"
  name: &dataset_name "Toys_and_Games"

  kindle:
    sep: ","
    n_item: 7844
    train_test_split: 0.9
    num_negatives: 1
    user_threshold: 0
    item_threshold: 0
    rating_threshold: 0

  ml-1m:
    sep: "::"
    n_item: 3952
    train_test_split: 0.99
    num_negatives: 1
    user_threshold: 10
    item_threshold: 10
    rating_threshold: 2

  kuairec:
    sep: ","
    n_item: 10727
    train_test_split: 0.99
    num_negatives: 1
    user_threshold: 0
    item_threshold: 0
    rating_threshold: 0

  Toys_and_Games:
    sep: ","
    n_item: 27907
    train_test_split: 0.9
    num_negatives: 2
    user_threshold: 0
    item_threshold: 0
    rating_threshold: 0

  item_path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, "item.csv"]
  path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, "interaction.csv"]
  item_emb_path: !!python/object/apply:os.path.join [*base_path, "llm_emb", *dataset_name, "bert_emb64.npy"]

  base_model:
    - "acf"
    - "fdsa"
    - "harnn"
    - "caser"
    - "pfmc"
    - "sasrec"
    - "anam"
  base_model_path: !!python/object/apply:os.path.join [*base_path, "basemodel_results", *dataset_name]

model:
  name: "new_ensrec_wgts_div4_reg2"
  type: "ensrec_no_basemodel_no_llm"
  lr: 0.001
  hidden_dim: 64
  device: *device
  pretrain_llm: "bert-base-uncased"

  use_div: true
  div_tradeoff: 4
  use_reg: true
  reg_tradeoff: 2

  num_transformer_layers: 4
  num_attention_heads: 8
  intermediate_size: 256
  dropout_rate: 0.5

topk: 10
epoch: 20
batch_size: 512
