base_path: &base_path "D:/Code/graduation_design/"
# base_path: &base_path "/root/autodl-tmp/graduation_design/"

data:
  sep: "::"
  maxlen: 5
  base_model_topk: 100
  train_test_split: 0.99
  device: &device "cpu"
  name: &dataset_name "magazine"

  item_path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, "item.dat"]
  item_emb_path: !!python/object/apply:os.path.join [*base_path, "llm_emb", *dataset_name, "bert_emb64.npy"]
  path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, 'interaction.dat']

  num_negatives: 1
  user_threshold: 2
  item_threshold: 2
  rating_threshold: 2

  base_model:
    - "acf"
    - "fdsa"
    - "harnn"
    - "caser"
    - "pfmc"
    - "sasrec"
    - "anam"
  base_model_path: !!python/object/apply:os.path.join [*base_path, "base_model_results", *dataset_name]

model:
  name: "magazine_fixbug_reg"
  lr: 0.001
  hidden_dim: 64
  device: *device
  type: "bpr_ensrec"
  n_weak_learners: 10
  pretrain_llm: "bert-base-uncased"

  use_div: false
  div_tradeoff: 1
  use_reg: true
  reg_tradeoff: 1

topk: 10
epoch: 10
batch_size: 512
