base_path: &base_path "D:/Code/graduation_design/"
# base_path: &base_path "/graduation_design/"
topk: 10

data:
  sep: "::"
  maxlen: 20
  device: "cuda:0"
  # nrows: 100000
  base_model_topk: 100
  train_test_split: 0.99
  name: &dataset_name "ml-1m"

  item_path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, "movies.dat"]
  item_emb_path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, "item_embeddings.npy"]
  path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, 'ratings.dat']

  num_negatives: 1
  user_threshold: 10
  item_threshold: 10
  rating_threshold: 2

  base_model:
    - "acf"
    - "fdsa"
    - "harnn"
    - "caser"
    - "pfmc"
    - "sasrec"
    - "anam"
  base_model_path: !!python/object/apply:os.path.join [*base_path, "base_model_results", *dataset_name]

model:
  lr: 0.001
  type: "softmax"
  hidden_dim: 32
  pretrain_llm: "bert-base-uncased"

epoch: 1
batch_size: 512
