# base_path: &base_path "D:/Code/graduation_design/"
base_path: &base_path "/graduation_design/"
topk: 10

data:
  train_valid_split: 0.7
  nrows: 100000
  maxlen: 30
  name: &dataset_name "ml-1m"
  sep: "::"
  item_path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, "movies.dat"]
  item_emb_path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, "item_embeddings.npy"]
  path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, 'ratings.dat']

  num_negatives: 1
  user_threshold: 10
  item_threshold: 10
  rating_threshold: 2

  base_model:
    - "acf"
    - "fdsa"
    - "harnn"
    - "caser"
    - "pfmc"
    - "sasrec"
    - "anam"
  base_model_path: !!python/object/apply:os.path.join [*base_path, "base_model_results", *dataset_name]

model:
  lr: 0.001
  type: "SASEM"
  lamda: 0.00001
  hidden_dim: 32
  device: "cuda:0"
  optimizer: "AdamOptimizer"

  tradeoff: 2
  div_module: "cov"
  pretrain_llm: "bert-base-uncased"

epoch: 1
batch_size: 512
