seed: 0
neighbor_cnt: 5
model: "anam"

lamda:
  acf: 0.001
  fdsa: 0.01
  pfmc: 0.00001
  caser: 0.000001
  anam: 0.0001
  harnn: 0.0001

dataset:
  sep: ","
  name: "Toys_and_Games"
  path: "../data/Toys_and_Games"

train:
  factor: 64
  batch_size: 2048
  epoch: 150
  lr: 0.001
  optimizer: "AdamOptimizer"
