seed: 0
neighbor_cnt: 5
model: "sasrec"

lamda:
  acf: 0.001
  fdsa: 0.01
  pfmc: 0.00001
  caser: 0.000001
  anam: 0.0001
  harnn: 0.0001

dataset:
  name: "magazine"
  path: "D:/Code/graduation_design/data/magazine"

train:
  factor: 64
  batch_size: 2048
  epoch: 100
  lr: 0.001
  optimizer: "AdamOptimizer"
