base_path: &base_path "D:/Code/graduation_design/"
# base_path: &base_path "/root/autodl-tmp/graduation_design/"

data:
  maxlen: 20
  name: &dataset_name "ml-1m"
  item_path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, "movies.dat"]
  item_emb_path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name, "item_embeddings.npy"]
  path: !!python/object/apply:os.path.join [*base_path, "data", *dataset_name]

  user_drop_threshold: 10
  item_drop_threshold: 10

meta:
  base_model:
    - "acf"
    - "fdsa"
    - "harnn"
    - "caser"
    - "pfmc"
    - "sasrec"
    - "anam"
  path: !!python/object/apply:os.path.join [*base_path, "base_model_results", *dataset_name]

model:
  lr: 0.001
  type: "SASEM"
  lamda: 0.00001
  hidden_dim: 32
  device: "cuda:0"
  optimizer: "AdamOptimizer"
  user_module: "SAtt"
  model_module: "dynamic"

  tradeoff: 2
  div_module: "cov"
  pretrain_llm: "bert-base-uncased"

train:
  epoch: 10
  batch_size: 512
